INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_ANDERSONDARLING andersondarling)

FIND_PATH(
    ANDERSONDARLING_INCLUDE_DIRS
    NAMES andersondarling/api.h
    HINTS $ENV{ANDERSONDARLING_DIR}/include
        ${PC_ANDERSONDARLING_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    ANDERSONDARLING_LIBRARIES
    NAMES gnuradio-andersondarling
    HINTS $ENV{ANDERSONDARLING_DIR}/lib
        ${PC_ANDERSONDARLING_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ANDERSONDARLING DEFAULT_MSG ANDERSONDARLING_LIBRARIES ANDERSONDARLING_INCLUDE_DIRS)
MARK_AS_ADVANCED(ANDERSONDARLING_LIBRARIES ANDERSONDARLING_INCLUDE_DIRS)

